### ISSUE TITLE
Voter List - Group Observers on Top

### ISSUE THREAD

**Issue by rcuisnier** [saramorillon/mini-planning#7]
Hello,

Could you groups observer on top of voter list ?

Best Regards,
Romain.

**Comment by saramorillon** [comment]
Hello,
Thank you for your feedback. I understand that the presence of observers in the voters' table hinders the reading of the table. I have therefore removed the observers from the voters' table and placed them in a list above the table. I hope this will meet your needs.
Done in v1.2.0
